### ISSUE TITLE
Docker container aria2 exited with nonzero status.

### ISSUE THREAD

**Issue by Phill23** [timonier/aria2#1]
Hello,
I can't start the latest build. I have an older version running in a container with no problems.

**Comment by mauchede** [comment]
Hello @Phill23,

I changed the entrypoint in the last version. In theory, you just have to add `aria2c` in your command(s):

```sh
# old image
docker run timonier/aria2 --dir /data --enable-rpc --rpc-listen-all

# last image
docker run timonier/aria2 aria2c --dir /data --enable-rpc --rpc-listen-all
```

**Comment by Phill23** [comment]
Thanks, and sorry for not double-check on changes!

**Comment by mauchede** [comment]
I am glad to see that your problem is fixed (and glad to see that my project is used!). I am going to close this issue. Do not hesitate to open a new one if you have any problem.
