### ISSUE TITLE
errorCode=1 https is not supported yet. 

### ISSUE THREAD

**Issue by Phill23** [timonier/aria2#2]
Thanks again for the build!
Since I installed the latest version I cannot download https links anymore.
I found this issue report : [https://github.com/aria2/aria2/issues/779](https://github.com/aria2/aria2/issues/779)
I am no coder so sorry if I did something not right.
this is what I did:

```
docker run \
-d \
--restart=always \
--name aria2c \
-p 6800:6800/tcp \
-v /containers/aria2:/config \
-v /downloads:/mnt/downloads \
-e PUID=0 \
-e PGID=0 \
-e ARIA2_VERSION=1.18.10 \
-e PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
--network=host \
timonier/aria2 aria2c --dir=/mnt/downloads --enable-rpc --rpc-listen-all=true --on-download-complete=/config/mvcompleted.sh
```

I also build an alpine container inside which I ran `apk add --update aria2` than added the same variables I use for ur image but here it works...

**Comment by mauchede** [comment]
Hello @Phill23,

Good catch! I will fix this problem this afternoon.

**Comment by mauchede** [comment]
I added the missing libraries. It should be OK now.

Can you retrieve the latest version and tell me if it is OK for you?

**Comment by Phill23** [comment]
Just tested and it works, thanks!

**Comment by mauchede** [comment]
You are welcome! I am going to close this issue. If you have any problem / question about this image, do not hesitate to open a new issue.
